/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change password
         * @description Changes the signed-in user's password after verifying the current one, then revokes every refresh token so all sessions must re-authenticate.
         */
        post: operations["post-auth-change-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset
         * @description Emails a password-reset link if the address matches an active account. Always succeeds, so the response cannot be used to probe which emails are registered.
         */
        post: operations["post-auth-forgot-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/impersonate/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop impersonating
         * @description Ends the current impersonation session and restores the administrator session by refreshing the preserved admin refresh cookie.
         */
        post: operations["post-auth-impersonate-stop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/impersonate/{targetUserId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Impersonate a user
         * @description Starts impersonating another user. Requires an administrator (the * permission); administrators cannot be impersonated. Returns an impersonation session and sets the access cookie, leaving the admin's refresh cookie intact so the session can be restored.
         */
        post: operations["post-auth-impersonate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description Returns the profile for the bearer access token.
         */
        get: operations["get-auth-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update own profile
         * @description Updates the calling user's own profile fields (displayName, avatarUrl, phone, jobTitle, company). Status and role assignments are not editable through this path — those require an admin via PATCH /api/users/{id}.
         */
        patch: operations["patch-auth-me"];
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh session
         * @description Rotates the refresh token cookie and returns a new access token. Refused (409) while impersonating — use the stop-impersonation endpoint instead.
         */
        post: operations["post-auth-refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend the email verification link
         * @description Issues a fresh email-verification link for the signed-in user. A no-op when the email is already verified.
         */
        post: operations["post-auth-resend-verification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset a password with a token
         * @description Sets a new password using a token from the forgot-password email, then revokes every session for the account.
         */
        post: operations["post-auth-reset-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Authenticates credentials, returns an access token, and sets the refresh token cookie.
         */
        post: operations["post-auth-sign-in"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Revokes the current refresh token cookie when present.
         */
        post: operations["post-auth-sign-out"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-out-others": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out other sessions
         * @description Revokes every other active session for the current user, keeping the calling device signed in. Requires the current refresh token cookie to identify which session to keep.
         */
        post: operations["post-auth-sign-out-others"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign up
         * @description Creates a user account, returns an access token, and sets the refresh token cookie.
         */
        post: operations["post-auth-sign-up"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify an email address
         * @description Confirms an email address using a verification token from the sign-up email.
         */
        post: operations["post-auth-verify-email"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List notifications
         * @description Returns the authenticated user's notifications, newest first, with their unread count.
         */
        get: operations["list-notifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark all notifications read
         * @description Marks every unread notification for the authenticated user read.
         */
        post: operations["mark-all-notifications-read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark a notification read
         * @description Marks one of the authenticated user's notifications read. Idempotent; returns the updated unread count.
         */
        post: operations["mark-notification-read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List assignable permissions
         * @description Returns the catalog of permissions an admin can assign to a role. Requires the roles:read permission.
         */
        get: operations["list-permissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects
         * @description Returns a paginated list of projects owned by the authenticated user.
         */
        get: operations["get-projects"];
        put?: never;
        /**
         * Create project
         * @description Creates a new project owned by the authenticated user. Requires the projects:create permission.
         */
        post: operations["post-projects"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get project by id
         * @description Returns a single project owned by the authenticated user.
         */
        get: operations["get-project"];
        put?: never;
        post?: never;
        /**
         * Archive project
         * @description Archives a project owned by the authenticated user. Sets status to archived rather than physically deleting; idempotent for already-archived projects.
         */
        delete: operations["delete-project"];
        options?: never;
        head?: never;
        /**
         * Update project
         * @description Partially updates a project owned by the authenticated user. Omitted fields stay unchanged; an empty description clears the field; at least one field must be provided.
         */
        patch: operations["patch-project"];
        trace?: never;
    };
    "/api/projects/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List project members
         * @description Lists the non-owner members of a project. Any user with access to the project may view its members.
         */
        get: operations["get-project-members"];
        put?: never;
        /**
         * Add a project member
         * @description Grants a user, identified by email, viewer or editor access to a project. Owner only.
         */
        post: operations["post-project-member"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a project member
         * @description Revokes a user's access to a project. Owner only.
         */
        delete: operations["delete-project-member"];
        options?: never;
        head?: never;
        /**
         * Update a project member role
         * @description Changes an existing member's access role. Owner only.
         */
        patch: operations["patch-project-member"];
        trace?: never;
    };
    "/api/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List roles
         * @description Returns every role with its permissions and assigned-user count. Requires the roles:read permission.
         */
        get: operations["list-roles"];
        put?: never;
        /**
         * Create a role
         * @description Creates a custom role from assignable catalog permissions. Requires the roles:manage permission.
         */
        post: operations["create-role"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get role by id
         * @description Returns a single role by id. Requires the roles:read permission.
         */
        get: operations["get-role"];
        put?: never;
        post?: never;
        /**
         * Delete a role
         * @description Deletes a custom role. Requires the roles:manage permission. System roles, and roles still assigned to users, cannot be deleted.
         */
        delete: operations["delete-role"];
        options?: never;
        head?: never;
        /**
         * Update a role
         * @description Updates a custom role's name, description, and/or permission set. Requires the roles:manage permission. System roles cannot be modified.
         */
        patch: operations["update-role"];
        trace?: never;
    };
    "/api/system-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List system events
         * @description Returns recent system audit events. Requires the system_events:read permission.
         */
        get: operations["get-system-events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Returns a paginated list of users. Requires the users:read permission.
         */
        get: operations["get-users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user by id
         * @description Returns a single user by id. Requires the users:read permission.
         */
        get: operations["get-user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update user status or roles
         * @description Updates a user's status and/or replaces their role set. Requires the users:manage permission. An admin cannot change their own account.
         */
        patch: operations["patch-user"];
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Checks if the service is alive.
         */
        get: operations["get-healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Checks if the service is ready to handle traffic.
         */
        get: operations["get-readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddProjectMemberInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AddProjectMemberInputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: email
             * @description Email of the user to grant access to
             * @example teammate@example.com
             */
            email: string;
            /**
             * @description Access role to grant
             * @example editor
             * @enum {string}
             */
            role: "viewer" | "editor";
        };
        AuthMeBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AuthMeBody.json
             */
            readonly $schema?: string;
            /** @description Authenticated user profile with roles and permissions */
            user: components["schemas"]["AuthMeUser"];
        };
        AuthMeUser: {
            /**
             * @description User avatar image URL; empty when unset
             * @example
             */
            avatarUrl: string;
            /**
             * @description User company; empty when unset
             * @example
             */
            company: string;
            /**
             * @description User display name
             * @example Demo User
             */
            displayName: string;
            /**
             * @description User email address
             * @example demo@wow-dashboard.test
             */
            email: string;
            /**
             * @description Whether the user has confirmed their email address
             * @example true
             */
            emailVerified: boolean;
            /**
             * @description User identifier
             * @example c8a89c0b-8e75-4e61-9fa0-70fb83554e66
             */
            id: string;
            /** @description Email of the admin impersonating this user; absent unless impersonating */
            impersonatorEmail?: string;
            /** @description Id of the admin impersonating this user; absent unless impersonating */
            impersonatorId?: string;
            /**
             * @description User job title; empty when unset
             * @example
             */
            jobTitle: string;
            /**
             * Format: date-time
             * @description Last successful sign-in time; null if the user has never signed in
             */
            lastLoginAt?: string;
            /** @description Effective permission strings granted by the user's roles */
            permissions: string[];
            /**
             * @description User phone number; empty when unset
             * @example
             */
            phone: string;
            /** @description Names of the roles assigned to the user */
            roles: string[];
        };
        AuthSessionBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AuthSessionBody.json
             */
            readonly $schema?: string;
            /** @description Authenticated user profile */
            user: components["schemas"]["AuthUser"];
        };
        AuthSuccessBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AuthSuccessBody.json
             */
            readonly $schema?: string;
            /**
             * @description Operation success flag
             * @example true
             */
            success: boolean;
        };
        AuthUser: {
            /**
             * @description User display name
             * @example Demo User
             */
            displayName: string;
            /**
             * @description User email address
             * @example demo@wow-dashboard.test
             */
            email: string;
            /**
             * @description User identifier
             * @example c8a89c0b-8e75-4e61-9fa0-70fb83554e66
             */
            id: string;
        };
        ChangePasswordInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ChangePasswordInputBody.json
             */
            readonly $schema?: string;
            /** @description The user's current password */
            currentPassword: string;
            /** @description The new password (minimum 8 characters) */
            newPassword: string;
        };
        CreateProjectInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateProjectInputBody.json
             */
            readonly $schema?: string;
            /**
             * @description Optional project description
             * @example
             */
            description?: string;
            /**
             * @description Project name
             * @example Demo Project
             */
            name: string;
            /**
             * @description Optional status; defaults to active
             * @example active
             */
            status?: string;
        };
        CreateRoleInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateRoleInputBody.json
             */
            readonly $schema?: string;
            /**
             * @description Optional role description
             * @example Read-only access to audit data
             */
            description?: string;
            /**
             * @description Unique role name
             * @example auditor
             */
            name: string;
            /** @description Permission strings to grant; each must be an assignable catalog permission */
            permissions?: string[] | null;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        ForgotPasswordInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ForgotPasswordInputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: email
             * @description Email address to send a reset link to
             * @example demo@wow-dashboard.test
             */
            email: string;
        };
        HealthResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HealthResponseBody.json
             */
            readonly $schema?: string;
            /**
             * @description The status of the application
             * @example ok
             */
            status: string;
        };
        NotificationItem: {
            /**
             * @description Optional longer text
             * @example An administrator changed your roles.
             */
            body: string;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createdAt: string;
            /**
             * @description Notification identifier
             * @example c8a89c0b-8e75-4e61-9fa0-70fb83554e66
             */
            id: string;
            /** @description Safe JSON object metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Format: date-time
             * @description When the user read the notification; absent while unread
             */
            readAt?: string;
            /**
             * @description Short headline
             * @example Your roles were updated
             */
            title: string;
            /**
             * @description Stable notification type
             * @example users.roles.updated
             */
            type: string;
        };
        NotificationsListBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/NotificationsListBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Requested limit after defaulting
             * @example 20
             */
            limit: number;
            /** @description Opaque cursor for the next page; absent when there are no more notifications */
            nextCursor?: string;
            /** @description The user's notifications, newest first */
            notifications: components["schemas"]["NotificationItem"][];
            /**
             * Format: int64
             * @description Total unread notifications for the user, independent of this page
             * @example 3
             */
            unreadCount: number;
        };
        PatchMeInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PatchMeInputBody.json
             */
            readonly $schema?: string;
            /** @description New avatar URL or inline data URL; omit to leave unchanged */
            avatarUrl?: string;
            /** @description New company; omit to leave unchanged */
            company?: string;
            /** @description New display name; omit to leave unchanged */
            displayName?: string;
            /** @description New job title; omit to leave unchanged */
            jobTitle?: string;
            /** @description New phone number; omit to leave unchanged */
            phone?: string;
        };
        PermissionsListBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PermissionsListBody.json
             */
            readonly $schema?: string;
            /** @description Every permission an admin can assign to a role */
            permissions: string[];
        };
        ProjectDetailBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ProjectDetailBody.json
             */
            readonly $schema?: string;
            /** @description Requested project */
            project: components["schemas"]["ProjectItem"];
        };
        ProjectItem: {
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createdAt: string;
            /**
             * @description Project description
             * @example
             */
            description: string;
            /**
             * @description Project identifier
             * @example c8a89c0b-8e75-4e61-9fa0-70fb83554e66
             */
            id: string;
            /**
             * @description Project name
             * @example Demo Project
             */
            name: string;
            /**
             * @description Owner user identifier
             * @example c8a89c0b-8e75-4e61-9fa0-70fb83554e66
             */
            ownerUserId: string;
            /**
             * @description Project status
             * @example active
             */
            status: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updatedAt: string;
        };
        ProjectMemberBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ProjectMemberBody.json
             */
            readonly $schema?: string;
            /** @description The project access grant */
            member: components["schemas"]["ProjectMemberGrant"];
        };
        ProjectMemberDeletedBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ProjectMemberDeletedBody.json
             */
            readonly $schema?: string;
            /**
             * @description Operation success flag
             * @example true
             */
            success: boolean;
        };
        ProjectMemberGrant: {
            /**
             * Format: date-time
             * @description Grant creation timestamp
             */
            createdAt: string;
            /**
             * @description Member access role
             * @example editor
             */
            role: string;
            /**
             * Format: date-time
             * @description Grant last update timestamp
             */
            updatedAt: string;
            /**
             * @description Member user identifier
             * @example d1f6b2a4-1c3e-4a8b-9d2f-6e7a0b1c2d3e
             */
            userId: string;
        };
        ProjectMemberItem: {
            /**
             * Format: date-time
             * @description Grant creation timestamp
             */
            createdAt: string;
            /**
             * @description Member display name
             * @example Team Mate
             */
            displayName: string;
            /**
             * @description Member email address
             * @example teammate@example.com
             */
            email: string;
            /**
             * @description Member access role
             * @example editor
             */
            role: string;
            /**
             * Format: date-time
             * @description Grant last update timestamp
             */
            updatedAt: string;
            /**
             * @description Member user identifier
             * @example d1f6b2a4-1c3e-4a8b-9d2f-6e7a0b1c2d3e
             */
            userId: string;
        };
        ProjectMembersBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ProjectMembersBody.json
             */
            readonly $schema?: string;
            /** @description Users granted non-owner access to the project */
            members: components["schemas"]["ProjectMemberItem"][];
        };
        ProjectsListBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ProjectsListBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Current page number
             * @example 1
             */
            page: number;
            /**
             * Format: int64
             * @description Projects per page
             * @example 20
             */
            pageSize: number;
            /** @description Projects for the requested page */
            projects: components["schemas"]["ProjectItem"][];
            /**
             * Format: int64
             * @description Total projects matching the filters
             * @example 1
             */
            total: number;
        };
        ReadyResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ReadyResponseBody.json
             */
            readonly $schema?: string;
            /**
             * @description The readiness status of the application
             * @example ready
             */
            status: string;
        };
        ResetPasswordInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ResetPasswordInputBody.json
             */
            readonly $schema?: string;
            /** @description The new password (minimum 8 characters) */
            newPassword: string;
            /** @description The reset token from the email */
            token: string;
        };
        RoleBody: {
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createdAt: string;
            /**
             * @description Role description
             * @example Read-only access to audit data
             */
            description: string;
            /**
             * @description Role identifier
             * @example c8a89c0b-8e75-4e61-9fa0-70fb83554e66
             */
            id: string;
            /**
             * @description Whether this is a built-in role that cannot be modified
             * @example false
             */
            isSystem: boolean;
            /**
             * @description Role name
             * @example auditor
             */
            name: string;
            /** @description Permission strings granted by the role */
            permissions: string[];
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updatedAt: string;
            /**
             * Format: int64
             * @description Number of users currently assigned this role
             * @example 3
             */
            userCount: number;
        };
        RoleDeletedBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RoleDeletedBody.json
             */
            readonly $schema?: string;
            /**
             * @description Deletion success flag
             * @example true
             */
            success: boolean;
        };
        RoleDetailBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RoleDetailBody.json
             */
            readonly $schema?: string;
            /** @description Requested role */
            role: components["schemas"]["RoleBody"];
        };
        RolesListBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RolesListBody.json
             */
            readonly $schema?: string;
            /** @description All roles */
            roles: components["schemas"]["RoleBody"][];
        };
        SignInInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SignInInputBody.json
             */
            readonly $schema?: string;
            /**
             * @description Email address
             * @example demo@wow-dashboard.test
             */
            email: string;
            /**
             * @description Account password
             * @example @Password
             */
            password: string;
        };
        SignUpInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SignUpInputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: email
             * @description Email address
             * @example hello@gmail.com
             */
            email: string;
            /**
             * @description First name
             * @example Hello
             */
            firstName: string;
            /**
             * @description Last name
             * @example Friend
             */
            lastName: string;
            /**
             * @description Account password
             * @example @Password
             */
            password: string;
        };
        SystemEventItem: {
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createdAt: string;
            /**
             * @description Stable system event type
             * @example projects.project.created
             */
            eventType: string;
            /**
             * @description System event identifier
             * @example c8a89c0b-8e75-4e61-9fa0-70fb83554e66
             */
            id: string;
            /**
             * @description Safe human-readable audit message
             * @example Project created.
             */
            message: string;
            /** @description Safe JSON object metadata recorded by audit writers */
            metadata: {
                [key: string]: unknown;
            };
        };
        SystemEventsListBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SystemEventsListBody.json
             */
            readonly $schema?: string;
            /** @description System audit events, newest first */
            events: components["schemas"]["SystemEventItem"][];
            /**
             * Format: int64
             * @description Requested event limit after defaulting
             * @example 20
             */
            limit: number;
            /** @description Opaque cursor for the next page; absent when there are no more events */
            nextCursor?: string;
        };
        UnreadCountBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UnreadCountBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description The user's unread notification count after the operation
             * @example 2
             */
            unreadCount: number;
        };
        UpdateProjectInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateProjectInputBody.json
             */
            readonly $schema?: string;
            /**
             * @description New project description; pass an empty string to clear, omit to leave unchanged
             * @example New description
             */
            description?: string;
            /**
             * @description New project name; omit to leave unchanged
             * @example New name
             */
            name?: string;
            /**
             * @description New project status (active or archived); omit to leave unchanged
             * @example active
             */
            status?: string;
        };
        UpdateProjectMemberInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateProjectMemberInputBody.json
             */
            readonly $schema?: string;
            /**
             * @description New access role
             * @example viewer
             * @enum {string}
             */
            role: "viewer" | "editor";
        };
        UpdateRoleInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateRoleInputBody.json
             */
            readonly $schema?: string;
            /** @description New description; omit to leave unchanged */
            description?: string;
            /** @description New name; omit to leave unchanged */
            name?: string;
            /** @description Replacement permission set; omit to leave unchanged */
            permissions?: string[];
        };
        UpdateUserInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateUserInputBody.json
             */
            readonly $schema?: string;
            /** @description New avatar URL or inline data URL; omit to leave unchanged */
            avatarUrl?: string;
            /** @description New company; omit to leave unchanged */
            company?: string;
            /** @description New job title; omit to leave unchanged */
            jobTitle?: string;
            /** @description New phone number; omit to leave unchanged */
            phone?: string;
            /** @description Replacement set of role ids; omit to leave roles unchanged */
            roleIds?: string[];
            /**
             * @description New status; omit to leave unchanged
             * @example active
             * @enum {string}
             */
            status?: "active" | "disabled";
        };
        UserDetailBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UserDetailBody.json
             */
            readonly $schema?: string;
            /** @description Requested user */
            user: components["schemas"]["UsersListItem"];
        };
        UsersListBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UsersListBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Current page number
             * @example 1
             */
            page: number;
            /**
             * Format: int64
             * @description Users per page
             * @example 20
             */
            pageSize: number;
            /**
             * Format: int64
             * @description Total users matching the filters
             * @example 1
             */
            total: number;
            /** @description Users for the requested page */
            users: components["schemas"]["UsersListItem"][];
        };
        UsersListItem: {
            /**
             * @description User avatar image URL; empty when unset
             * @example
             */
            avatarUrl: string;
            /**
             * @description User company; empty when unset
             * @example
             */
            company: string;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createdAt: string;
            /**
             * @description User display name
             * @example Demo User
             */
            displayName: string;
            /**
             * @description User email address
             * @example demo@wow-dashboard.test
             */
            email: string;
            /**
             * @description Whether the user's email is verified
             * @example false
             */
            emailVerified: boolean;
            /**
             * @description User identifier
             * @example c8a89c0b-8e75-4e61-9fa0-70fb83554e66
             */
            id: string;
            /**
             * @description User job title; empty when unset
             * @example
             */
            jobTitle: string;
            /**
             * Format: date-time
             * @description Last successful sign-in time; null if the user has never signed in
             */
            lastLoginAt?: string;
            /**
             * @description User phone number; empty when unset
             * @example
             */
            phone: string;
            /** @description Names of the roles assigned to the user */
            roles: string[];
            /**
             * @description User status
             * @example active
             */
            status: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updatedAt: string;
        };
        VerifyEmailInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/VerifyEmailInputBody.json
             */
            readonly $schema?: string;
            /** @description The verification token from the email */
            token: string;
        };
    };
    responses: {
        /** @description Project API error envelope */
        APIError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /**
                     * @description Machine-readable error code
                     * @example unauthorized
                     */
                    code: string;
                    /** @description Optional field-level error details */
                    details?: {
                        /** @description Field associated with the error */
                        field?: string;
                        /** @description Safe detail message */
                        message: string;
                    }[];
                    /**
                     * @description Safe client-facing error message
                     * @example Authorization token missing or invalid.
                     */
                    message: string;
                    /**
                     * @description Request ID for tracing
                     * @example abc-123-def
                     */
                    request_id: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "post-auth-change-password": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSuccessBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "post-auth-forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSuccessBody"];
                };
            };
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "post-auth-impersonate-stop": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token of the impersonation session */
                Authorization?: string;
                /** @description Refresh token cookie (the admin's, preserved during impersonation) */
                Cookie?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "post-auth-impersonate": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token of an administrator */
                Authorization?: string;
            };
            path: {
                /** @description Id of the user to impersonate */
                targetUserId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "get-auth-me": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "patch-auth-me": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchMeInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "post-auth-refresh": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token, if any; used to refuse refresh during impersonation */
                Authorization?: string;
                /** @description Refresh token cookie */
                Cookie?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            409: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "post-auth-resend-verification": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSuccessBody"];
                };
            };
            401: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "post-auth-reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSuccessBody"];
                };
            };
            401: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "post-auth-sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionBody"];
                };
            };
            400: components["responses"]["APIError"];
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            429: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "post-auth-sign-out": {
        parameters: {
            query?: never;
            header?: {
                /** @description Refresh token cookie */
                Cookie?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSuccessBody"];
                };
            };
            500: components["responses"]["APIError"];
        };
    };
    "post-auth-sign-out-others": {
        parameters: {
            query?: never;
            header?: {
                /** @description Refresh token cookie identifying the session to keep */
                Cookie?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSuccessBody"];
                };
            };
            401: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "post-auth-sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionBody"];
                };
            };
            400: components["responses"]["APIError"];
            409: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            429: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "post-auth-verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSuccessBody"];
                };
            };
            401: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "list-notifications": {
        parameters: {
            query?: {
                /** @description Maximum number of notifications per page; defaults to 20 and must not exceed 100 */
                limit?: number;
                /** @description When true, return only unread notifications */
                unreadOnly?: boolean;
                /** @description Opaque pagination cursor from a previous response's nextCursor; returns the next page of older notifications */
                cursor?: string;
            };
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationsListBody"];
                };
            };
            401: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "mark-all-notifications-read": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadCountBody"];
                };
            };
            401: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "mark-notification-read": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path: {
                /** @description Notification identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadCountBody"];
                };
            };
            401: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "list-permissions": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionsListBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "get-projects": {
        parameters: {
            query?: {
                /** @description Page number, defaults to 1 */
                page?: number;
                /** @description Projects per page, defaults to 20 and must not exceed 100 */
                pageSize?: number;
                /** @description Optional name or description search term */
                search?: string;
                /** @description Optional status filter: active or archived */
                status?: string;
            };
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectsListBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "post-projects": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailBody"];
                };
            };
            400: components["responses"]["APIError"];
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            409: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "get-project": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path: {
                /** @description Project UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            404: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "delete-project": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path: {
                /** @description Project UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            404: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "patch-project": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path: {
                /** @description Project UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailBody"];
                };
            };
            400: components["responses"]["APIError"];
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            404: components["responses"]["APIError"];
            409: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "get-project-members": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path: {
                /** @description Project UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMembersBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            404: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "post-project-member": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path: {
                /** @description Project UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddProjectMemberInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMemberBody"];
                };
            };
            400: components["responses"]["APIError"];
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            404: components["responses"]["APIError"];
            409: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "delete-project-member": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path: {
                /** @description Project UUID */
                id: string;
                /** @description Member user UUID */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMemberDeletedBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            404: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "patch-project-member": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path: {
                /** @description Project UUID */
                id: string;
                /** @description Member user UUID */
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectMemberInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMemberBody"];
                };
            };
            400: components["responses"]["APIError"];
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            404: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "list-roles": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolesListBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "create-role": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDetailBody"];
                };
            };
            400: components["responses"]["APIError"];
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            409: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "get-role": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path: {
                /** @description Role UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDetailBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            404: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "delete-role": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path: {
                /** @description Role UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDeletedBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            404: components["responses"]["APIError"];
            409: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "update-role": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path: {
                /** @description Role UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDetailBody"];
                };
            };
            400: components["responses"]["APIError"];
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            404: components["responses"]["APIError"];
            409: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "get-system-events": {
        parameters: {
            query?: {
                /** @description Maximum number of events to return per page; defaults to 20 and must not exceed 100 */
                limit?: number;
                /** @description Filter to a single stable event type */
                eventType?: string;
                /** @description Only events created at or after this RFC3339 timestamp */
                after?: string;
                /** @description Only events created strictly before this RFC3339 timestamp */
                before?: string;
                /** @description Opaque pagination cursor from a previous response's nextCursor; returns the next page of older events */
                cursor?: string;
            };
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemEventsListBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "get-users": {
        parameters: {
            query?: {
                /** @description Page number, defaults to 1 */
                page?: number;
                /** @description Users per page, defaults to 20 and must not exceed 100 */
                pageSize?: number;
                /** @description Optional email or display name search term */
                search?: string;
                /** @description Optional role name filter */
                role?: string;
                /** @description Optional status filter: active or disabled */
                status?: string;
            };
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsersListBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "get-user": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path: {
                /** @description User UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            404: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "patch-user": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path: {
                /** @description User UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailBody"];
                };
            };
            400: components["responses"]["APIError"];
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            404: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "get-healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponseBody"];
                };
            };
            503: components["responses"]["APIError"];
        };
    };
}
