/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description Returns the profile for the bearer access token.
         */
        get: operations["get-auth-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh session
         * @description Rotates the refresh token cookie and returns a new access token.
         */
        post: operations["post-auth-refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Authenticates credentials, returns an access token, and sets the refresh token cookie.
         */
        post: operations["post-auth-sign-in"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Revokes the current refresh token cookie when present.
         */
        post: operations["post-auth-sign-out"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign up
         * @description Creates a user account, returns an access token, and sets the refresh token cookie.
         */
        post: operations["post-auth-sign-up"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects
         * @description Returns a paginated list of projects owned by the authenticated user.
         */
        get: operations["get-projects"];
        put?: never;
        /**
         * Create project
         * @description Creates a new project owned by the authenticated user.
         */
        post: operations["post-projects"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get project by id
         * @description Returns a single project owned by the authenticated user.
         */
        get: operations["get-project"];
        put?: never;
        post?: never;
        /**
         * Archive project
         * @description Archives a project owned by the authenticated user. Sets status to archived rather than physically deleting; idempotent for already-archived projects.
         */
        delete: operations["delete-project"];
        options?: never;
        head?: never;
        /**
         * Update project
         * @description Partially updates a project owned by the authenticated user. Omitted fields stay unchanged; an empty description clears the field; at least one field must be provided.
         */
        patch: operations["patch-project"];
        trace?: never;
    };
    "/api/system-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List system events
         * @description Returns recent system audit events. Admin role required; non-admin authenticated users receive 403.
         */
        get: operations["get-system-events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Returns a paginated list of users. Admin role required; non-admin authenticated users receive 403.
         */
        get: operations["get-users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user by id
         * @description Returns a single user by id. Admin role required; non-admin authenticated users receive 403.
         */
        get: operations["get-user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Checks if the service is alive.
         */
        get: operations["get-healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Checks if the service is ready to handle traffic.
         */
        get: operations["get-readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthMeBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AuthMeBody.json
             */
            readonly $schema?: string;
            /** @description Authenticated user profile */
            user: components["schemas"]["AuthUser"];
        };
        AuthSessionBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AuthSessionBody.json
             */
            readonly $schema?: string;
            /** @description JWT access token */
            accessToken: string;
            /** @description Authenticated user profile */
            user: components["schemas"]["AuthUser"];
        };
        AuthSuccessBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AuthSuccessBody.json
             */
            readonly $schema?: string;
            /**
             * @description Operation success flag
             * @example true
             */
            success: boolean;
        };
        AuthUser: {
            /**
             * @description User display name
             * @example Demo User
             */
            displayName: string;
            /**
             * @description User email address
             * @example demo@minimals.cc
             */
            email: string;
            /**
             * @description User identifier
             * @example c8a89c0b-8e75-4e61-9fa0-70fb83554e66
             */
            id: string;
            /**
             * @description User role
             * @example user
             */
            role: string;
        };
        CreateProjectInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateProjectInputBody.json
             */
            readonly $schema?: string;
            /**
             * @description Optional project description
             * @example
             */
            description?: string;
            /**
             * @description Project name
             * @example Demo Project
             */
            name: string;
            /**
             * @description Optional status; defaults to active
             * @example active
             */
            status?: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        HealthResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HealthResponseBody.json
             */
            readonly $schema?: string;
            /**
             * @description The status of the application
             * @example ok
             */
            status: string;
        };
        ProjectDetailBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ProjectDetailBody.json
             */
            readonly $schema?: string;
            /** @description Requested project */
            project: components["schemas"]["ProjectItem"];
        };
        ProjectItem: {
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createdAt: string;
            /**
             * @description Project description
             * @example
             */
            description: string;
            /**
             * @description Project identifier
             * @example c8a89c0b-8e75-4e61-9fa0-70fb83554e66
             */
            id: string;
            /**
             * @description Project name
             * @example Demo Project
             */
            name: string;
            /**
             * @description Owner user identifier
             * @example c8a89c0b-8e75-4e61-9fa0-70fb83554e66
             */
            ownerUserId: string;
            /**
             * @description Project status
             * @example active
             */
            status: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updatedAt: string;
        };
        ProjectsListBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ProjectsListBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Current page number
             * @example 1
             */
            page: number;
            /**
             * Format: int64
             * @description Projects per page
             * @example 20
             */
            pageSize: number;
            /** @description Projects for the requested page */
            projects: components["schemas"]["ProjectItem"][];
            /**
             * Format: int64
             * @description Total projects matching the filters
             * @example 1
             */
            total: number;
        };
        ReadyResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ReadyResponseBody.json
             */
            readonly $schema?: string;
            /**
             * @description The readiness status of the application
             * @example ready
             */
            status: string;
        };
        SignInInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SignInInputBody.json
             */
            readonly $schema?: string;
            /**
             * @description Email address
             * @example demo@minimals.cc
             */
            email: string;
            /**
             * @description Account password
             * @example @2Minimal
             */
            password: string;
        };
        SignUpInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SignUpInputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: email
             * @description Email address
             * @example hello@gmail.com
             */
            email: string;
            /**
             * @description First name
             * @example Hello
             */
            firstName: string;
            /**
             * @description Last name
             * @example Friend
             */
            lastName: string;
            /**
             * @description Account password
             * @example @2Minimal
             */
            password: string;
        };
        SystemEventItem: {
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createdAt: string;
            /**
             * @description Stable system event type
             * @example projects.project.created
             */
            eventType: string;
            /**
             * @description System event identifier
             * @example c8a89c0b-8e75-4e61-9fa0-70fb83554e66
             */
            id: string;
            /**
             * @description Safe human-readable audit message
             * @example Project created.
             */
            message: string;
            /** @description Safe JSON object metadata recorded by audit writers */
            metadata: {
                [key: string]: unknown;
            };
        };
        SystemEventsListBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SystemEventsListBody.json
             */
            readonly $schema?: string;
            /** @description Recent system audit events */
            events: components["schemas"]["SystemEventItem"][];
            /**
             * Format: int64
             * @description Requested event limit after defaulting
             * @example 20
             */
            limit: number;
        };
        UpdateProjectInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateProjectInputBody.json
             */
            readonly $schema?: string;
            /**
             * @description New project description; pass an empty string to clear, omit to leave unchanged
             * @example New description
             */
            description?: string;
            /**
             * @description New project name; omit to leave unchanged
             * @example New name
             */
            name?: string;
            /**
             * @description New project status (active or archived); omit to leave unchanged
             * @example active
             */
            status?: string;
        };
        UserDetailBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UserDetailBody.json
             */
            readonly $schema?: string;
            /** @description Requested user */
            user: components["schemas"]["UsersListItem"];
        };
        UsersListBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UsersListBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Current page number
             * @example 1
             */
            page: number;
            /**
             * Format: int64
             * @description Users per page
             * @example 20
             */
            pageSize: number;
            /**
             * Format: int64
             * @description Total users matching the filters
             * @example 1
             */
            total: number;
            /** @description Users for the requested page */
            users: components["schemas"]["UsersListItem"][];
        };
        UsersListItem: {
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createdAt: string;
            /**
             * @description User display name
             * @example Demo User
             */
            displayName: string;
            /**
             * @description User email address
             * @example demo@minimals.cc
             */
            email: string;
            /**
             * @description User identifier
             * @example c8a89c0b-8e75-4e61-9fa0-70fb83554e66
             */
            id: string;
            /**
             * @description User role
             * @example admin
             */
            role: string;
            /**
             * @description User status
             * @example active
             */
            status: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updatedAt: string;
        };
    };
    responses: {
        /** @description Project API error envelope */
        APIError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /**
                     * @description Machine-readable error code
                     * @example unauthorized
                     */
                    code: string;
                    /** @description Optional field-level error details */
                    details?: {
                        /** @description Field associated with the error */
                        field?: string;
                        /** @description Safe detail message */
                        message: string;
                    }[];
                    /**
                     * @description Safe client-facing error message
                     * @example Authorization token missing or invalid.
                     */
                    message: string;
                    /**
                     * @description Request ID for tracing
                     * @example abc-123-def
                     */
                    request_id: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-auth-me": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "post-auth-refresh": {
        parameters: {
            query?: never;
            header?: {
                /** @description Refresh token cookie */
                Cookie?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "post-auth-sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionBody"];
                };
            };
            400: components["responses"]["APIError"];
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            429: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "post-auth-sign-out": {
        parameters: {
            query?: never;
            header?: {
                /** @description Refresh token cookie */
                Cookie?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSuccessBody"];
                };
            };
            500: components["responses"]["APIError"];
        };
    };
    "post-auth-sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionBody"];
                };
            };
            400: components["responses"]["APIError"];
            409: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            429: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "get-projects": {
        parameters: {
            query?: {
                /** @description Page number, defaults to 1 */
                page?: number;
                /** @description Projects per page, defaults to 20 and must not exceed 100 */
                pageSize?: number;
                /** @description Optional name or description search term */
                search?: string;
                /** @description Optional status filter: active or archived */
                status?: string;
            };
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectsListBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "post-projects": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailBody"];
                };
            };
            400: components["responses"]["APIError"];
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            409: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "get-project": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path: {
                /** @description Project UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            404: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "delete-project": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path: {
                /** @description Project UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            404: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "patch-project": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path: {
                /** @description Project UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailBody"];
                };
            };
            400: components["responses"]["APIError"];
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            404: components["responses"]["APIError"];
            409: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "get-system-events": {
        parameters: {
            query?: {
                /** @description Maximum number of recent system events to return; defaults to 20 and must not exceed 100 */
                limit?: number;
            };
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemEventsListBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "get-users": {
        parameters: {
            query?: {
                /** @description Page number, defaults to 1 */
                page?: number;
                /** @description Users per page, defaults to 20 and must not exceed 100 */
                pageSize?: number;
                /** @description Optional email or display name search term */
                search?: string;
                /** @description Optional role filter: admin or user */
                role?: string;
                /** @description Optional status filter: active or disabled */
                status?: string;
            };
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsersListBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "get-user": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer access token */
                Authorization?: string;
            };
            path: {
                /** @description User UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailBody"];
                };
            };
            401: components["responses"]["APIError"];
            403: components["responses"]["APIError"];
            404: components["responses"]["APIError"];
            422: components["responses"]["APIError"];
            500: components["responses"]["APIError"];
        };
    };
    "get-healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponseBody"];
                };
            };
            503: components["responses"]["APIError"];
        };
    };
}
