// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: auth_tokens.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthToken = `-- name: CreateAuthToken :exec
INSERT INTO auth_tokens (id, user_id, purpose, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAuthTokenParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Purpose   string
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) error {
	_, err := q.db.Exec(ctx, createAuthToken,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteAuthTokensForUser = `-- name: DeleteAuthTokensForUser :exec
DELETE FROM auth_tokens
WHERE user_id = $1 AND purpose = $2
`

type DeleteAuthTokensForUserParams struct {
	UserID  pgtype.UUID
	Purpose string
}

// Invalidates any outstanding tokens of a purpose for a user, so issuing a new
// one supersedes the old.
func (q *Queries) DeleteAuthTokensForUser(ctx context.Context, arg DeleteAuthTokensForUserParams) error {
	_, err := q.db.Exec(ctx, deleteAuthTokensForUser, arg.UserID, arg.Purpose)
	return err
}

const deleteConsumedOrExpiredAuthTokens = `-- name: DeleteConsumedOrExpiredAuthTokens :execrows
DELETE FROM auth_tokens
WHERE used_at IS NOT NULL OR expires_at < now()
`

// Retention purge: drop tokens that are already consumed (used_at set) or expired.
func (q *Queries) DeleteConsumedOrExpiredAuthTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConsumedOrExpiredAuthTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuthTokenByHash = `-- name: GetAuthTokenByHash :one
SELECT id, user_id, purpose, token_hash, expires_at, used_at, created_at
FROM auth_tokens
WHERE token_hash = $1 AND purpose = $2
`

type GetAuthTokenByHashParams struct {
	TokenHash string
	Purpose   string
}

func (q *Queries) GetAuthTokenByHash(ctx context.Context, arg GetAuthTokenByHashParams) (AuthToken, error) {
	row := q.db.QueryRow(ctx, getAuthTokenByHash, arg.TokenHash, arg.Purpose)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markAuthTokenUsed = `-- name: MarkAuthTokenUsed :exec
UPDATE auth_tokens
SET used_at = $1
WHERE id = $2
`

type MarkAuthTokenUsedParams struct {
	UsedAt pgtype.Timestamptz
	ID     pgtype.UUID
}

func (q *Queries) MarkAuthTokenUsed(ctx context.Context, arg MarkAuthTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markAuthTokenUsed, arg.UsedAt, arg.ID)
	return err
}
