// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: mfa.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMfaRecoveryCode = `-- name: CreateMfaRecoveryCode :exec
INSERT INTO user_mfa_recovery_codes (id, user_id, code_hash, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateMfaRecoveryCodeParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	CodeHash  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateMfaRecoveryCode(ctx context.Context, arg CreateMfaRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, createMfaRecoveryCode,
		arg.ID,
		arg.UserID,
		arg.CodeHash,
		arg.CreatedAt,
	)
	return err
}

const deleteMfaRecoveryCodesForUser = `-- name: DeleteMfaRecoveryCodesForUser :exec
DELETE FROM user_mfa_recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteMfaRecoveryCodesForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMfaRecoveryCodesForUser, userID)
	return err
}

const deleteUserMfaSecret = `-- name: DeleteUserMfaSecret :exec
DELETE FROM user_mfa_secrets WHERE user_id = $1
`

func (q *Queries) DeleteUserMfaSecret(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserMfaSecret, userID)
	return err
}

const getUserMfaSecret = `-- name: GetUserMfaSecret :one
SELECT id, user_id, secret_encrypted, algorithm, digits, period, created_at, updated_at
FROM user_mfa_secrets
WHERE user_id = $1
`

func (q *Queries) GetUserMfaSecret(ctx context.Context, userID pgtype.UUID) (UserMfaSecret, error) {
	row := q.db.QueryRow(ctx, getUserMfaSecret, userID)
	var i UserMfaSecret
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SecretEncrypted,
		&i.Algorithm,
		&i.Digits,
		&i.Period,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserMfaEnabled = `-- name: SetUserMfaEnabled :exec
UPDATE users
SET mfa_enabled = $1,
    mfa_confirmed_at = $2,
    updated_at = $3
WHERE id = $4
`

type SetUserMfaEnabledParams struct {
	MfaEnabled     bool
	MfaConfirmedAt pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ID             pgtype.UUID
}

func (q *Queries) SetUserMfaEnabled(ctx context.Context, arg SetUserMfaEnabledParams) error {
	_, err := q.db.Exec(ctx, setUserMfaEnabled,
		arg.MfaEnabled,
		arg.MfaConfirmedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertUserMfaSecret = `-- name: UpsertUserMfaSecret :one
INSERT INTO user_mfa_secrets (id, user_id, secret_encrypted, algorithm, digits, period, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id) DO UPDATE
SET secret_encrypted = EXCLUDED.secret_encrypted,
    algorithm = EXCLUDED.algorithm,
    digits = EXCLUDED.digits,
    period = EXCLUDED.period,
    updated_at = EXCLUDED.updated_at
RETURNING id, user_id, secret_encrypted, algorithm, digits, period, created_at, updated_at
`

type UpsertUserMfaSecretParams struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	SecretEncrypted string
	Algorithm       string
	Digits          int32
	Period          int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// Setup replaces any in-progress (unconfirmed) secret for the user; the UNIQUE
// user_id makes this an upsert.
func (q *Queries) UpsertUserMfaSecret(ctx context.Context, arg UpsertUserMfaSecretParams) (UserMfaSecret, error) {
	row := q.db.QueryRow(ctx, upsertUserMfaSecret,
		arg.ID,
		arg.UserID,
		arg.SecretEncrypted,
		arg.Algorithm,
		arg.Digits,
		arg.Period,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UserMfaSecret
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SecretEncrypted,
		&i.Algorithm,
		&i.Digits,
		&i.Period,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
