// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Purpose   string
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Notification struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Type      string
	Title     string
	Body      string
	Metadata  []byte
	ReadAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Project struct {
	ID          pgtype.UUID
	Name        string
	Description string
	Status      string
	OwnerUserID pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ProjectMember struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RefreshToken struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	TokenHash         string
	FamilyID          pgtype.UUID
	ExpiresAt         pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	ReplacedByTokenID pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	UserAgent         pgtype.Text
	IpAddress         pgtype.Text
	LastUsedAt        pgtype.Timestamptz
}

type Role struct {
	ID          pgtype.UUID
	Name        string
	Description string
	IsSystem    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type RolePermission struct {
	RoleID     pgtype.UUID
	Permission string
}

type SystemEvent struct {
	ID        pgtype.UUID
	EventType string
	Message   string
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID               pgtype.UUID
	Email            string
	DisplayName      string
	PasswordHash     string
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	FailedLoginCount int32
	LockedUntil      pgtype.Timestamptz
	EmailVerifiedAt  pgtype.Timestamptz
	AvatarUrl        pgtype.Text
	Phone            pgtype.Text
	JobTitle         pgtype.Text
	Company          pgtype.Text
	LastLoginAt      pgtype.Timestamptz
	MfaEnabled       bool
	MfaConfirmedAt   pgtype.Timestamptz
}

type UserMfaRecoveryCode struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	CodeHash  string
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type UserMfaSecret struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	SecretEncrypted string
	Algorithm       string
	Digits          int32
	Period          int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type UserRole struct {
	UserID pgtype.UUID
	RoleID pgtype.UUID
}
