// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: notifications.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*)
FROM notifications
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (id, user_id, type, title, body, metadata, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, type, title, body, metadata, read_at, created_at
`

type CreateNotificationParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Type      string
	Title     string
	Body      string
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Metadata,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsPage = `-- name: ListNotificationsPage :many
SELECT id, user_id, type, title, body, metadata, read_at, created_at
FROM notifications
WHERE user_id = $1
  AND (NOT $2::bool OR read_at IS NULL)
  AND (
    $3::timestamptz IS NULL
    OR created_at < $3
    OR (created_at = $3 AND id < $4)
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListNotificationsPageParams struct {
	UserID          pgtype.UUID
	UnreadOnly      bool
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	RowLimit        int32
}

// Keyset pagination over a user's notifications, newest first. unread_only
// restricts to unread rows; the (cursor_created_at, cursor_id) pair pages
// strictly past the previous page's last row. Callers fetch one extra row to
// detect whether a further page exists.
func (q *Queries) ListNotificationsPage(ctx context.Context, arg ListNotificationsPageParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsPage,
		arg.UserID,
		arg.UnreadOnly,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Metadata,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications
SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications
SET read_at = now()
WHERE id = $1 AND user_id = $2 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// Marks one notification read, scoped to its owner so a user can never touch
// another user's rows. Idempotent: an already-read or non-owned row matches
// nothing and affects zero rows.
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
