// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: projects.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveProject = `-- name: ArchiveProject :one
UPDATE projects
SET
    status = 'archived',
    updated_at = $1
WHERE id = $2 AND owner_user_id = $3
RETURNING id, name, description, status, owner_user_id, created_at, updated_at
`

type ArchiveProjectParams struct {
	UpdatedAt   pgtype.Timestamptz
	ID          pgtype.UUID
	OwnerUserID pgtype.UUID
}

func (q *Queries) ArchiveProject(ctx context.Context, arg ArchiveProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, archiveProject, arg.UpdatedAt, arg.ID, arg.OwnerUserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countProjectsPage = `-- name: CountProjectsPage :one
SELECT count(*)::bigint
FROM projects
WHERE owner_user_id = $1
AND (
    $2::text IS NULL
    OR name ILIKE '%' || $2::text || '%'
    OR description ILIKE '%' || $2::text || '%'
)
AND (
    $3::text IS NULL
    OR status = $3::text
)
`

type CountProjectsPageParams struct {
	OwnerUserID pgtype.UUID
	Search      pgtype.Text
	Status      pgtype.Text
}

func (q *Queries) CountProjectsPage(ctx context.Context, arg CountProjectsPageParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsPage, arg.OwnerUserID, arg.Search, arg.Status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, name, description, status, owner_user_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, description, status, owner_user_id, created_at, updated_at
`

type CreateProjectParams struct {
	ID          pgtype.UUID
	Name        string
	Description string
	Status      string
	OwnerUserID pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.OwnerUserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, description, status, owner_user_id, created_at, updated_at
FROM projects
WHERE id = $1 AND owner_user_id = $2
`

type GetProjectByIDParams struct {
	ID          pgtype.UUID
	OwnerUserID pgtype.UUID
}

func (q *Queries) GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, arg.ID, arg.OwnerUserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsPage = `-- name: ListProjectsPage :many
SELECT id, name, description, status, owner_user_id, created_at, updated_at
FROM projects
WHERE owner_user_id = $1
AND (
    $2::text IS NULL
    OR name ILIKE '%' || $2::text || '%'
    OR description ILIKE '%' || $2::text || '%'
)
AND (
    $3::text IS NULL
    OR status = $3::text
)
ORDER BY created_at DESC, id DESC
LIMIT $5 OFFSET $4
`

type ListProjectsPageParams struct {
	OwnerUserID pgtype.UUID
	Search      pgtype.Text
	Status      pgtype.Text
	OffsetVal   int32
	LimitVal    int32
}

func (q *Queries) ListProjectsPage(ctx context.Context, arg ListProjectsPageParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsPage,
		arg.OwnerUserID,
		arg.Search,
		arg.Status,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.OwnerUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    name = COALESCE($1::text, name),
    description = COALESCE($2::text, description),
    status = COALESCE($3::text, status),
    updated_at = $4
WHERE id = $5 AND owner_user_id = $6
RETURNING id, name, description, status, owner_user_id, created_at, updated_at
`

type UpdateProjectParams struct {
	Name        pgtype.Text
	Description pgtype.Text
	Status      pgtype.Text
	UpdatedAt   pgtype.Timestamptz
	ID          pgtype.UUID
	OwnerUserID pgtype.UUID
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
		arg.OwnerUserID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
