// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: project_members.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProjectMember = `-- name: CreateProjectMember :one
INSERT INTO project_members (project_id, user_id, role, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING project_id, user_id, role, created_at, updated_at
`

type CreateProjectMemberParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateProjectMember(ctx context.Context, arg CreateProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, createProjectMember,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectMember = `-- name: DeleteProjectMember :execrows
DELETE FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type DeleteProjectMemberParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) DeleteProjectMember(ctx context.Context, arg DeleteProjectMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectMember, arg.ProjectID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT project_id, user_id, role, created_at, updated_at
FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type GetProjectMemberParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, getProjectMember, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT m.project_id, m.user_id, m.role, m.created_at, m.updated_at,
       u.email, u.display_name
FROM project_members m
JOIN users u ON u.id = m.user_id
WHERE m.project_id = $1
ORDER BY m.created_at ASC, m.user_id ASC
`

type ListProjectMembersRow struct {
	ProjectID   pgtype.UUID
	UserID      pgtype.UUID
	Role        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Email       string
	DisplayName string
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID pgtype.UUID) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectMembersRow
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectMemberRole = `-- name: UpdateProjectMemberRole :one
UPDATE project_members
SET role = $1, updated_at = $2
WHERE project_id = $3 AND user_id = $4
RETURNING project_id, user_id, role, created_at, updated_at
`

type UpdateProjectMemberRoleParams struct {
	Role      string
	UpdatedAt pgtype.Timestamptz
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, updateProjectMemberRole,
		arg.Role,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.UserID,
	)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
