// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: refresh_tokens.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    id,
    user_id,
    token_hash,
    family_id,
    expires_at,
    revoked_at,
    replaced_by_token_id,
    created_at,
    updated_at,
    user_agent,
    ip_address,
    last_used_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    NULL,
    NULL,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING
    id,
    user_id,
    token_hash,
    family_id,
    expires_at,
    revoked_at,
    replaced_by_token_id,
    created_at,
    updated_at,
    user_agent,
    ip_address,
    last_used_at
`

type CreateRefreshTokenParams struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TokenHash  string
	FamilyID   pgtype.UUID
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	UserAgent  pgtype.Text
	IpAddress  pgtype.Text
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.FamilyID,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserAgent,
		arg.IpAddress,
		arg.LastUsedAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedByTokenID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens
WHERE expires_at < now()
`

// Retention purge: drop refresh tokens that have already expired. Revoked but
// not-yet-expired tokens are kept so reuse detection still recognises them.
func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT
    id,
    user_id,
    token_hash,
    family_id,
    expires_at,
    revoked_at,
    replaced_by_token_id,
    created_at,
    updated_at,
    user_agent,
    ip_address,
    last_used_at
FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedByTokenID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.LastUsedAt,
	)
	return i, err
}

const listActiveSessionsByUserID = `-- name: ListActiveSessionsByUserID :many
SELECT
    id,
    user_id,
    token_hash,
    family_id,
    expires_at,
    revoked_at,
    replaced_by_token_id,
    created_at,
    updated_at,
    user_agent,
    ip_address,
    last_used_at
FROM refresh_tokens
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
ORDER BY last_used_at DESC NULLS LAST, created_at DESC
`

// One row per active session (refresh-token family): the family's current,
// non-revoked, unexpired token, carrying the device metadata captured at
// sign-in. Most-recently-used first.
func (q *Queries) ListActiveSessionsByUserID(ctx context.Context, userID pgtype.UUID) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, listActiveSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshToken
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.FamilyID,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.ReplacedByTokenID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserAgent,
			&i.IpAddress,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens
SET
    revoked_at = $1,
    updated_at = $1
WHERE user_id = $2
  AND revoked_at IS NULL
`

type RevokeAllUserRefreshTokensParams struct {
	RevokedAt pgtype.Timestamptz
	UserID    pgtype.UUID
}

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, arg RevokeAllUserRefreshTokensParams) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, arg.RevokedAt, arg.UserID)
	return err
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :exec
UPDATE refresh_tokens
SET
    revoked_at = $1,
    updated_at = $1
WHERE token_hash = $2
  AND revoked_at IS NULL
`

type RevokeRefreshTokenByHashParams struct {
	RevokedAt pgtype.Timestamptz
	TokenHash string
}

func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, arg RevokeRefreshTokenByHashParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenByHash, arg.RevokedAt, arg.TokenHash)
	return err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE refresh_tokens
SET
    revoked_at = $1,
    updated_at = $1
WHERE family_id = $2
  AND revoked_at IS NULL
`

type RevokeRefreshTokenFamilyParams struct {
	RevokedAt pgtype.Timestamptz
	FamilyID  pgtype.UUID
}

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, arg RevokeRefreshTokenFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, arg.RevokedAt, arg.FamilyID)
	return err
}

const revokeUserRefreshTokenFamily = `-- name: RevokeUserRefreshTokenFamily :execrows
UPDATE refresh_tokens
SET
    revoked_at = $1,
    updated_at = $1
WHERE user_id = $2
  AND family_id = $3
  AND revoked_at IS NULL
`

type RevokeUserRefreshTokenFamilyParams struct {
	RevokedAt pgtype.Timestamptz
	UserID    pgtype.UUID
	FamilyID  pgtype.UUID
}

// Revoke one session (family) belonging to the user. Scoped by user_id so a
// user can never revoke another account's session; rows affected = 0 means the
// family was not the user's active session (wrong id or already revoked).
func (q *Queries) RevokeUserRefreshTokenFamily(ctx context.Context, arg RevokeUserRefreshTokenFamilyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserRefreshTokenFamily, arg.RevokedAt, arg.UserID, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserRefreshTokensExceptFamily = `-- name: RevokeUserRefreshTokensExceptFamily :exec
UPDATE refresh_tokens
SET
    revoked_at = $1,
    updated_at = $1
WHERE user_id = $2
  AND family_id <> $3
  AND revoked_at IS NULL
`

type RevokeUserRefreshTokensExceptFamilyParams struct {
	RevokedAt pgtype.Timestamptz
	UserID    pgtype.UUID
	FamilyID  pgtype.UUID
}

// Revoke every active session for the user except the caller's current token
// family, so "sign out other sessions" leaves the calling device signed in.
func (q *Queries) RevokeUserRefreshTokensExceptFamily(ctx context.Context, arg RevokeUserRefreshTokensExceptFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeUserRefreshTokensExceptFamily, arg.RevokedAt, arg.UserID, arg.FamilyID)
	return err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :one
WITH revoked AS (
    UPDATE refresh_tokens AS old_token
    SET
        revoked_at = $11,
        replaced_by_token_id = $1,
        updated_at = $11
    WHERE old_token.id = $12
      AND old_token.revoked_at IS NULL
    RETURNING id
)
INSERT INTO refresh_tokens (
    id,
    user_id,
    token_hash,
    family_id,
    expires_at,
    revoked_at,
    replaced_by_token_id,
    created_at,
    updated_at,
    user_agent,
    ip_address,
    last_used_at
)
SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    NULL,
    NULL,
    $6,
    $7,
    $8,
    $9,
    $10
WHERE EXISTS (SELECT 1 FROM revoked)
RETURNING
    id,
    user_id,
    token_hash,
    family_id,
    expires_at,
    revoked_at,
    replaced_by_token_id,
    created_at,
    updated_at,
    user_agent,
    ip_address,
    last_used_at
`

type RotateRefreshTokenParams struct {
	NewID      pgtype.UUID
	UserID     pgtype.UUID
	TokenHash  string
	FamilyID   pgtype.UUID
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	UserAgent  pgtype.Text
	IpAddress  pgtype.Text
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	OldID      pgtype.UUID
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, rotateRefreshToken,
		arg.NewID,
		arg.UserID,
		arg.TokenHash,
		arg.FamilyID,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserAgent,
		arg.IpAddress,
		arg.LastUsedAt,
		arg.RevokedAt,
		arg.OldID,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedByTokenID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.LastUsedAt,
	)
	return i, err
}
