// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: roles.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRolesByIDs = `-- name: CountRolesByIDs :one
SELECT count(*)::bigint
FROM roles
WHERE id = ANY ($1::uuid[])
`

func (q *Queries) CountRolesByIDs(ctx context.Context, ids []pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRolesByIDs, ids)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, is_system, created_at, updated_at
FROM roles
WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
