// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: system_events.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSystemEvent = `-- name: CreateSystemEvent :one
INSERT INTO system_events (id, event_type, message, metadata, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, event_type, message, metadata, created_at
`

type CreateSystemEventParams struct {
	ID        pgtype.UUID
	EventType string
	Message   string
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateSystemEvent(ctx context.Context, arg CreateSystemEventParams) (SystemEvent, error) {
	row := q.db.QueryRow(ctx, createSystemEvent,
		arg.ID,
		arg.EventType,
		arg.Message,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i SystemEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Message,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getSystemEvent = `-- name: GetSystemEvent :one
SELECT id, event_type, message, metadata, created_at
FROM system_events
WHERE id = $1
`

func (q *Queries) GetSystemEvent(ctx context.Context, id pgtype.UUID) (SystemEvent, error) {
	row := q.db.QueryRow(ctx, getSystemEvent, id)
	var i SystemEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Message,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listSystemEvents = `-- name: ListSystemEvents :many
SELECT id, event_type, message, metadata, created_at
FROM system_events
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListSystemEvents(ctx context.Context, limit int32) ([]SystemEvent, error) {
	rows, err := q.db.Query(ctx, listSystemEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemEvent
	for rows.Next() {
		var i SystemEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Message,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
