// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: users.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, display_name, password_hash, status, role, created_at, updated_at)
VALUES ($1, lower($2), $3, $4, $5, $6, $7, $8)
RETURNING id, email, display_name, status, role, created_at, updated_at
`

type CreateUserParams struct {
	ID           pgtype.UUID
	Email        string
	DisplayName  string
	PasswordHash string
	Status       string
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type CreateUserRow struct {
	ID          pgtype.UUID
	Email       string
	DisplayName string
	Status      string
	Role        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Status,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, status, role, created_at, updated_at
FROM users
WHERE email = lower($1)
`

type GetUserByEmailRow struct {
	ID          pgtype.UUID
	Email       string
	DisplayName string
	Status      string
	Role        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailForAuth = `-- name: GetUserByEmailForAuth :one
SELECT id, email, display_name, password_hash, status, role, created_at, updated_at
FROM users
WHERE email = lower($1)
`

type GetUserByEmailForAuthRow struct {
	ID           pgtype.UUID
	Email        string
	DisplayName  string
	PasswordHash string
	Status       string
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetUserByEmailForAuth(ctx context.Context, email string) (GetUserByEmailForAuthRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailForAuth, email)
	var i GetUserByEmailForAuthRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, status, role, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID          pgtype.UUID
	Email       string
	DisplayName string
	Status      string
	Role        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, display_name, status, role, created_at, updated_at
FROM users
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListUsersParams struct {
	OffsetVal int32
	LimitVal  int32
}

type ListUsersRow struct {
	ID          pgtype.UUID
	Email       string
	DisplayName string
	Status      string
	Role        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Status,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET status = $1, updated_at = now()
WHERE id = $2
RETURNING id, email, display_name, status, role, created_at, updated_at
`

type UpdateUserStatusParams struct {
	Status string
	ID     pgtype.UUID
}

type UpdateUserStatusRow struct {
	ID          pgtype.UUID
	Email       string
	DisplayName string
	Status      string
	Role        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (UpdateUserStatusRow, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.Status, arg.ID)
	var i UpdateUserStatusRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDemoUser = `-- name: UpsertDemoUser :one
INSERT INTO users (id, email, display_name, password_hash, status, role, created_at, updated_at)
VALUES ($1, lower($2), $3, $4, $5, $6, $7, $8)
ON CONFLICT (email) DO UPDATE
SET display_name = EXCLUDED.display_name,
    password_hash = EXCLUDED.password_hash,
    status = EXCLUDED.status,
    role = EXCLUDED.role,
    updated_at = EXCLUDED.updated_at
RETURNING id, email, display_name, status, role, created_at, updated_at
`

type UpsertDemoUserParams struct {
	ID           pgtype.UUID
	Email        string
	DisplayName  string
	PasswordHash string
	Status       string
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UpsertDemoUserRow struct {
	ID          pgtype.UUID
	Email       string
	DisplayName string
	Status      string
	Role        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpsertDemoUser(ctx context.Context, arg UpsertDemoUserParams) (UpsertDemoUserRow, error) {
	row := q.db.QueryRow(ctx, upsertDemoUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Status,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UpsertDemoUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
