// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: users_list.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersPage = `-- name: CountUsersPage :one
SELECT count(*)::bigint
FROM users
WHERE (
    $1::text IS NULL
    OR email ILIKE '%' || $1::text || '%'
    OR display_name ILIKE '%' || $1::text || '%'
)
AND (
    $2::text IS NULL
    OR role = $2::text
)
AND (
    $3::text IS NULL
    OR status = $3::text
)
`

type CountUsersPageParams struct {
	Search pgtype.Text
	Role   pgtype.Text
	Status pgtype.Text
}

func (q *Queries) CountUsersPage(ctx context.Context, arg CountUsersPageParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersPage, arg.Search, arg.Role, arg.Status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listUsersPage = `-- name: ListUsersPage :many
SELECT id, email, display_name, status, role, created_at, updated_at
FROM users
WHERE (
    $1::text IS NULL
    OR email ILIKE '%' || $1::text || '%'
    OR display_name ILIKE '%' || $1::text || '%'
)
AND (
    $2::text IS NULL
    OR role = $2::text
)
AND (
    $3::text IS NULL
    OR status = $3::text
)
ORDER BY created_at DESC, id DESC
LIMIT $5 OFFSET $4
`

type ListUsersPageParams struct {
	Search    pgtype.Text
	Role      pgtype.Text
	Status    pgtype.Text
	OffsetVal int32
	LimitVal  int32
}

type ListUsersPageRow struct {
	ID          pgtype.UUID
	Email       string
	DisplayName string
	Status      string
	Role        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListUsersPage(ctx context.Context, arg ListUsersPageParams) ([]ListUsersPageRow, error) {
	rows, err := q.db.Query(ctx, listUsersPage,
		arg.Search,
		arg.Role,
		arg.Status,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersPageRow
	for rows.Next() {
		var i ListUsersPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Status,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
