// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: users.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearLoginFailures = `-- name: ClearLoginFailures :exec
UPDATE users
SET failed_login_count = 0,
    locked_until = NULL,
    last_login_at = $1,
    updated_at = $1
WHERE id = $2
`

type ClearLoginFailuresParams struct {
	UpdatedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

// Clears the failure counter and lock, and records the sign-in time, after a
// successful sign-in.
func (q *Queries) ClearLoginFailures(ctx context.Context, arg ClearLoginFailuresParams) error {
	_, err := q.db.Exec(ctx, clearLoginFailures, arg.UpdatedAt, arg.ID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, display_name, password_hash, status, created_at, updated_at)
VALUES ($1, lower($2), $3, $4, $5, $6, $7)
RETURNING id, email, display_name, status, created_at, updated_at
`

type CreateUserParams struct {
	ID           pgtype.UUID
	Email        string
	DisplayName  string
	PasswordHash string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type CreateUserRow struct {
	ID          pgtype.UUID
	Email       string
	DisplayName string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, status, created_at, updated_at
FROM users
WHERE email = lower($1)
`

type GetUserByEmailRow struct {
	ID          pgtype.UUID
	Email       string
	DisplayName string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailForAuth = `-- name: GetUserByEmailForAuth :one
SELECT id, email, display_name, password_hash, status, created_at, updated_at,
       failed_login_count, locked_until, email_verified_at,
       avatar_url, phone, job_title, company, last_login_at, mfa_enabled, mfa_confirmed_at
FROM users
WHERE email = lower($1)
`

func (q *Queries) GetUserByEmailForAuth(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailForAuth, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.EmailVerifiedAt,
		&i.AvatarUrl,
		&i.Phone,
		&i.JobTitle,
		&i.Company,
		&i.LastLoginAt,
		&i.MfaEnabled,
		&i.MfaConfirmedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, status, created_at, updated_at, email_verified_at,
       avatar_url, phone, job_title, company, last_login_at, mfa_enabled
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID              pgtype.UUID
	Email           string
	DisplayName     string
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	EmailVerifiedAt pgtype.Timestamptz
	AvatarUrl       pgtype.Text
	Phone           pgtype.Text
	JobTitle        pgtype.Text
	Company         pgtype.Text
	LastLoginAt     pgtype.Timestamptz
	MfaEnabled      bool
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.AvatarUrl,
		&i.Phone,
		&i.JobTitle,
		&i.Company,
		&i.LastLoginAt,
		&i.MfaEnabled,
	)
	return i, err
}

const getUserByIDForAuth = `-- name: GetUserByIDForAuth :one
SELECT id, email, display_name, password_hash, status, created_at, updated_at,
       failed_login_count, locked_until, email_verified_at,
       avatar_url, phone, job_title, company, last_login_at, mfa_enabled, mfa_confirmed_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByIDForAuth(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIDForAuth, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.EmailVerifiedAt,
		&i.AvatarUrl,
		&i.Phone,
		&i.JobTitle,
		&i.Company,
		&i.LastLoginAt,
		&i.MfaEnabled,
		&i.MfaConfirmedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, display_name, status, created_at, updated_at
FROM users
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListUsersParams struct {
	OffsetVal int32
	LimitVal  int32
}

type ListUsersRow struct {
	ID          pgtype.UUID
	Email       string
	DisplayName string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerLoginFailure = `-- name: RegisterLoginFailure :one
UPDATE users
SET failed_login_count = CASE
        WHEN failed_login_count + 1 >= $1::int THEN 0
        ELSE failed_login_count + 1
    END,
    locked_until = CASE
        WHEN failed_login_count + 1 >= $1::int THEN $2::timestamptz
        ELSE locked_until
    END,
    updated_at = $3
WHERE id = $4
RETURNING locked_until
`

type RegisterLoginFailureParams struct {
	MaxAttempts int32
	LockedUntil pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ID          pgtype.UUID
}

// Records a failed sign-in. On reaching @max_attempts the counter resets and
// the account is locked until @locked_until; returns the resulting lock time.
func (q *Queries) RegisterLoginFailure(ctx context.Context, arg RegisterLoginFailureParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, registerLoginFailure,
		arg.MaxAttempts,
		arg.LockedUntil,
		arg.UpdatedAt,
		arg.ID,
	)
	var locked_until pgtype.Timestamptz
	err := row.Scan(&locked_until)
	return locked_until, err
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE users
SET email_verified_at = $1, updated_at = $2
WHERE id = $3
`

type SetEmailVerifiedParams struct {
	VerifiedAt pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	ID         pgtype.UUID
}

func (q *Queries) SetEmailVerified(ctx context.Context, arg SetEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, setEmailVerified, arg.VerifiedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserFields = `-- name: UpdateUserFields :exec
UPDATE users
SET status = COALESCE($1::text, status),
    display_name = COALESCE($2::text, display_name),
    avatar_url = COALESCE($3::text, avatar_url),
    phone = COALESCE($4::text, phone),
    job_title = COALESCE($5::text, job_title),
    company = COALESCE($6::text, company),
    updated_at = $7
WHERE id = $8
`

type UpdateUserFieldsParams struct {
	Status      pgtype.Text
	DisplayName pgtype.Text
	AvatarUrl   pgtype.Text
	Phone       pgtype.Text
	JobTitle    pgtype.Text
	Company     pgtype.Text
	UpdatedAt   pgtype.Timestamptz
	ID          pgtype.UUID
}

// Applies a partial user update. Each field uses a nullable arg: NULL leaves
// the column unchanged, a value (including ”) overwrites it. Both the admin
// and the self-service handlers feed this query; each caller is responsible
// for restricting which fields it allows the actor to change.
func (q *Queries) UpdateUserFields(ctx context.Context, arg UpdateUserFieldsParams) error {
	_, err := q.db.Exec(ctx, updateUserFields,
		arg.Status,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Phone,
		arg.JobTitle,
		arg.Company,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $1, updated_at = $2
WHERE id = $3
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	UpdatedAt    pgtype.Timestamptz
	ID           pgtype.UUID
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	return err
}

const upsertDemoUser = `-- name: UpsertDemoUser :one
INSERT INTO users (id, email, display_name, password_hash, status, created_at, updated_at)
VALUES ($1, lower($2), $3, $4, $5, $6, $7)
ON CONFLICT (email) DO UPDATE
SET display_name = EXCLUDED.display_name,
    password_hash = EXCLUDED.password_hash,
    status = EXCLUDED.status,
    updated_at = EXCLUDED.updated_at
RETURNING id, email, display_name, status, created_at, updated_at
`

type UpsertDemoUserParams struct {
	ID           pgtype.UUID
	Email        string
	DisplayName  string
	PasswordHash string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UpsertDemoUserRow struct {
	ID          pgtype.UUID
	Email       string
	DisplayName string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpsertDemoUser(ctx context.Context, arg UpsertDemoUserParams) (UpsertDemoUserRow, error) {
	row := q.db.QueryRow(ctx, upsertDemoUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UpsertDemoUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
