// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: user_roles.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserRole = `-- name: AddUserRole :exec
INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
ON CONFLICT (user_id, role_id) DO NOTHING
`

type AddUserRoleParams struct {
	UserID pgtype.UUID
	RoleID pgtype.UUID
}

func (q *Queries) AddUserRole(ctx context.Context, arg AddUserRoleParams) error {
	_, err := q.db.Exec(ctx, addUserRole, arg.UserID, arg.RoleID)
	return err
}

const listUserPermissions = `-- name: ListUserPermissions :many
SELECT DISTINCT rp.permission
FROM user_roles ur
JOIN role_permissions rp ON rp.role_id = ur.role_id
WHERE ur.user_id = $1
`

func (q *Queries) ListUserPermissions(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT r.id, r.name
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
ORDER BY r.name ASC
`

type ListUserRolesRow struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) ListUserRoles(ctx context.Context, userID pgtype.UUID) ([]ListUserRolesRow, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRolesRow
	for rows.Next() {
		var i ListUserRolesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceUserRoles = `-- name: ReplaceUserRoles :exec
WITH added AS (
    INSERT INTO user_roles (user_id, role_id)
    SELECT $1, rid
    FROM unnest($2::uuid[]) AS rid
    ON CONFLICT (user_id, role_id) DO NOTHING
)
DELETE FROM user_roles
WHERE user_roles.user_id = $1
  AND user_roles.role_id <> ALL (COALESCE($2::uuid[], ARRAY[]::uuid[]))
`

type ReplaceUserRolesParams struct {
	UserID  pgtype.UUID
	RoleIds []pgtype.UUID
}

// Insert the new assignments first, then delete the ones no longer in the
// set. A data-modifying CTE shares one snapshot, so a DELETE-then-INSERT would
// not see its own deletes and would collide on rows common to both sets.
func (q *Queries) ReplaceUserRoles(ctx context.Context, arg ReplaceUserRolesParams) error {
	_, err := q.db.Exec(ctx, replaceUserRoles, arg.UserID, arg.RoleIds)
	return err
}
