// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: users_list.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersPage = `-- name: CountUsersPage :one
SELECT count(DISTINCT u.id)::bigint
FROM users u
WHERE (
    $1::text IS NULL
    OR u.email ILIKE '%' || $1::text || '%'
    OR u.display_name ILIKE '%' || $1::text || '%'
)
AND (
    $2::text IS NULL
    OR u.status = $2::text
)
AND (
    $3::text IS NULL
    OR EXISTS (
        SELECT 1 FROM user_roles ur2
        JOIN roles r2 ON r2.id = ur2.role_id
        WHERE ur2.user_id = u.id AND r2.name = $3::text
    )
)
`

type CountUsersPageParams struct {
	Search pgtype.Text
	Status pgtype.Text
	Role   pgtype.Text
}

func (q *Queries) CountUsersPage(ctx context.Context, arg CountUsersPageParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersPage, arg.Search, arg.Status, arg.Role)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listUsersPage = `-- name: ListUsersPage :many
SELECT
    u.id, u.email, u.display_name, u.status, u.created_at, u.updated_at,
    COALESCE(
        array_agg(DISTINCT r.name) FILTER (WHERE r.name IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles
FROM users u
LEFT JOIN user_roles ur ON ur.user_id = u.id
LEFT JOIN roles r ON r.id = ur.role_id
WHERE (
    $1::text IS NULL
    OR u.email ILIKE '%' || $1::text || '%'
    OR u.display_name ILIKE '%' || $1::text || '%'
)
AND (
    $2::text IS NULL
    OR u.status = $2::text
)
AND (
    $3::text IS NULL
    OR EXISTS (
        SELECT 1 FROM user_roles ur2
        JOIN roles r2 ON r2.id = ur2.role_id
        WHERE ur2.user_id = u.id AND r2.name = $3::text
    )
)
GROUP BY u.id
ORDER BY u.created_at DESC, u.id DESC
LIMIT $5 OFFSET $4
`

type ListUsersPageParams struct {
	Search    pgtype.Text
	Status    pgtype.Text
	Role      pgtype.Text
	OffsetVal int32
	LimitVal  int32
}

type ListUsersPageRow struct {
	ID          pgtype.UUID
	Email       string
	DisplayName string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Roles       []string
}

func (q *Queries) ListUsersPage(ctx context.Context, arg ListUsersPageParams) ([]ListUsersPageRow, error) {
	rows, err := q.db.Query(ctx, listUsersPage,
		arg.Search,
		arg.Status,
		arg.Role,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersPageRow
	for rows.Next() {
		var i ListUsersPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
